### ISSUE TITLE
Hello && Thanks

### ISSUE THREAD

**Issue by gingerbeardman** [EngineersNeedArt/SoftDorothy-UnfinishedTales-Vol2#1]
Hi John. I'm not sure of the best way to comment on your blog post, and this archive, so I'll do it here. 😬

Anyway, I'm a game developer mostly working on Playdate handheld console (1-bit, 400x240, close to the classic Macintosh) so I love seeing your old monochrome graphics. Even better to come to this repo and see more than were in the blog post. 

Just like you, I'm prolific in terms of prototyping and abandon things regularly. And I also have the philosophy that if the central gameplay mechanic itself is fun you've already won the battle. 

https://blog.gingerbeardman.com/2024/03/07/a-year-in-the-life-of-a-playdate-game-developer/

So I guess I could summarise my feelings on your latest blog post as: me, too!

Cheers and greetings from Liverpool, England.

matt

**Comment by EngineersNeedArt** [comment]
Hi, Matt — 

Very cool.

How is working on the Playdate? I’ve had one for a year or so but haven't tried to develop for it. I figured no one is making any money on the games anyway, ha ha. Looks like you took a stab at Pararena?

Glad to hear someone else thinks along the same lines as I do. The Playdate may be a good place too to enjoy (& employ) quick prototyping.

My youngest daughter, FWIW, is going to school up north from you right now — she just started a year abroad at Sterling (and is enjoying it apparently). I also have a (programmer) friend I have worked with and known for over 30 years (he also wrote games in the 90’s) who lives outside London. The wife and I have visited the U.K. twice.

You can email me directly at my last name @me.com

John Calhoun—

**Comment by gingerbeardman** [comment]
There's money to be made on Playdate, depends how much you're expecting. Building smaller games makes it totally worthwhile. I don't think it can support larger games with the current size of user base. The SDK is great, using Lua is very easy and prototypes just pop out. I have gravitated towards using primitives to construct my graphics so that I don't have to pixel as much, it's surprising what you can achieve this way. 

One of my games, YOYOZO, was featured on Ars Technica's GOTY 2023 list, next to Mario/Zelda/etc. Amazing. 

I got Pararena going but my physics (real-time) were ever so slightly janky and it put me off. My plan was to have crank control in some way, but I never got that far. 

My next Playdate game is scheduled for release early October. Meanwhile I've been doing some macOS/iOS apps and am all-in on an iOS logic puzzle game.

Will drop you an email
